isi2-projet/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EtudiantController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SousCategorieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/',[HomeController::class, 'index']);
Route::resource('etudiant',EtudiantController::class);
Route::resource('sous_categorie', SousCategorieController::class);


require __DIR__.'/auth.php';

isi2-projet/app/Models/Etudiant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DB;

class Etudiant extends Model
{
    use HasFactory;
    
    // obtenir la liste des utilisateurs
    public function getAll(){
        //$etudiants = DB::table('Utilisateur')->get();
        $etudiants = DB::select('SELECT * FROM Utilisateur U JOIN Etudiant_e_ E ON U.Id_U = E.Id_U');
        return $etudiants;
    }

    public function getOne(int $id){
        $etudiant = DB::table('Utilisateur')
        ->join('Etudiant_e_', 'Etudiant_e_.Id_U', '=', 'Utilisateur.Id_U')
        ->where('Etudiant_e_.Id_U', '=', $id)->get();
        return $etudiant;
    }

    /*
    protected $table = 'Etudiant_e_';
    protected $fillable = ['Id_U', 'description', 'Ville'];
    */

}

isi2-projet/app/Models/Sous_Categorie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DB;

class Sous_Categorie extends Model
{
    use HasFactory;

    // obtenir la liste des utilisateurs
    public function getAllSous_Cat(){
        $sous_categories = DB::table('Sous_Catégorie')
        ->join('Catégorie','Catégorie.Id_C', '=', 'Sous_Catégorie.Id_C')->get();
        return $sous_categories;
    }

    public function getService(int $id_c, int $id_sc){
        $services = DB::table('Service')
        ->join('Sous_Catégorie','Sous_Catégorie.Id_SC', '=', 'Service.Id_SC')
        ->where('Service.Id_SC','=', $id_sc)
        ->where('Service.Id_C',"=", $id_c)->get();
        return $services;
    }    
    
}

isi2-projet/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

isi2-projet/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

isi2-projet/app/Http/Controllers/EtudiantController.php
<?php

namespace App\Http\Controllers;

use App\Models\Etudiant;
use Illuminate\Http\Request;

class EtudiantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$etudiants = Etudiant::all();
        //return view('etudiant', compact($etudiants));
        $etudiant = new Etudiant();
        $etudiants = $etudiant->getAll();
        return view('etudiant', compact('etudiants'));
    }

    public function show(int $id)
    {
        $etudiant = new Etudiant();
        $etudiant->getOne($id);
        return view('etudiantProfil', compact('etudiant'));
    }
}

isi2-projet/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    //provide data to the home page
    public function index(){
        return view('home');
    }
}

isi2-projet/app/Http/Controllers/SousCategorieController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Sous_Categorie;

class SousCategorieController extends Controller
{

    public function index(){
        $sous_categorie = new Sous_Categorie();
        $sous_categories = $sous_categorie ->getAllSous_Cat();
        return view('sous_categorie', compact('sous_categories'));
    }

    public function show(Sous_Categorie $services){
        //$service = new Sous_Categorie();
        //$services = $service ->getService($id_c, $id_sc);
        $services ->getService((int)$services->Id_C, (int)$services->Id_SC);
        return view('service', compact('services'));
    }
}

isi2-projet/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

isi2-projet/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

isi2-projet/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

isi2-projet/resources/views/etudiant.blade.php
@extends('layouts.layout')

@section('titrePage')
    Etudiants
@endsection

@section('titreItem')
    <h2>Voici la liste de nos étudiants</h2>
@endsection

@section('contenu')
<table class ="table table-borderd table-stripted">
    <thead>
        <th>Prénom</th>
        <th>Nom</th>
        <th>E-mail</th>
        <th>Description</th>
        <th>Pour voir le profil</th>
    </thead>

    @foreach($etudiants as $etudiant)
        <tr>
            <td> {{ $etudiant->Prenom}} </td>
            <td> {{ $etudiant->Nom}} </td>
            <td> {{ $etudiant->Mail}} </td>
            <td> {{ $etudiant->description}} </td>
            <td><a class="btn btn-primary" href="{{route('etudiant.show', $etudiant->Id_U)}}"> 
                    <button class="btn btn-primary">Voir</button>
                </a>
            </td>
        </tr>
    @endforeach
</table>
@endsection

isi2-projet/resources/views/etudiantProfil.blade.php
@extends('layouts.layout')

@section('titrePage')
    Info étudiant
@endsection

@section('titreItem')
    <h2>Profil de l'étudiant</h2>
@endsection

@section('contenu')

<?php print_r($etudiant) ?>

<div class="card">
    <header class="card-header">
        <h5 class="card-header-title">Prenom : {{$etudiant->Prenom}}, Nom : {{$etudiant->Nom}}</h5>
    </header>
    <div class = "card-content">
        <div class="content">
            <p>Description : {{$etudiant->description}} Random</p>
            <p>Ville : {{$etudiant->ville}} Random</p>
            <hr>
            <p>Disponibilité :</p>
        </div>
    </div>
</div>

@endsection

isi2-projet/resources/views/home.blade.php
@extends('layouts.layout')
@section('titrePage')
Alo
@endsection


@section('titreItem')
<h2>Alo, le site qu'il vous faut</h2>
<img class=imgHome src='https://projetisi2.files.wordpress.com/2021/06/pexels-photo-2850438.jpeg'/>
@endsection

@section('contenu')

<h2>Un site qui vous permettra de trouver de l'aide rapidement</h2>
<div>
    <li><strong>Trouvez</strong> l'offre qui vous correspond à vos besoins parmi les annonces proposées par les étudiants</li>
    <li><strong>Réservez</strong> votre service après la mise en relation avec l'étudiant</li>
    <li><strong>Payez</strong> via une plateforme 100% sécurisé</li>
</div>
@endsection

isi2-projet/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

isi2-projet/resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

isi2-projet/resources/views/layouts/layout.blade.php
<!doctype html>
<html lang="fr">
	<head>
        <meta charset="utf-8">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
                
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2&display=swap" rel="stylesheet"> 
        
        <link href="{{ asset('css/style.css')}}" rel="stylesheet">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

        <title>
            @yield('titrePage')
        </title>
    </head>
     
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{url('/') }}">
                    <img class="logo" src="img/ALO.png"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{url('/') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Actualités</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('etudiant.index')}}">Etudiants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('sous_categorie.index')}}">Catégories</a>
                        </li>
                        <li class="nav-item dropdown">
                            @auth
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Bienvenu, {{Auth::user()->name}}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li>
                                    <a class="dropdown-item" href="{{route('logout')}}" method="POST" onclick="event.preventDefaut();
                                            document.getElementById('logout-form').submit();">
                                         {{__('Logout')}}
                                    </a>
                                    <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </li>
                            </ul>
                            @else
                            <li>
                                <a class="nav-link active" aria-current="page" href="{{route('login')}}">Login</a>
                            </li>
                            <li>
                                <a class="nav-link active" aria-current="page" href="{{route('register')}}">Register</a>
                            </li>
                            @endauth
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
        
        
        <header>
            @yield('titreItem')
        </header>

        <section>
            @yield('contenu')
        </section>
    </body>

    <footer class="footer">
        Alo - copyright 3AInfo - 2021
    </footer>
</html>

isi2-projet/resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

isi2-projet/resources/views/service.blade.php
@extends('layouts.layout')

@section('titrePage')
    Service
@endsection

@section('titreItem')
    <h2>Voici la liste de nos services pour la sous-catégorie</h2>
@endsection

@section('contenu')

    <div class="card" >
        <header class="card-header">
            <h5 class="card-header-title">Intérieur</h5>
        </header>
        @foreach($services as $service)
            <div class="list-group-item" style="text-align: center;">
                <li>random</li>
            </div>
        @endforeach    
    </div>

@endsection

isi2-projet/resources/views/sous_categorie.blade.php
@extends('layouts.layout')

@section('titrePage')
    Info étudiant
@endsection

@section('titreItem')
    <h2>Liste de nos catégories</h2>
@endsection

@section('contenu')

    <div class="card">
        <header class="card-header">
            <h5 class="card-header-title">Extérieur</h5>
        </header>
        @foreach($sous_categories as $sous_categorie)
            @if($sous_categorie->Id_C == 1)
            
            <div class="list-group-item" style="text-align: center;">
                <a href="{{route('sous_categorie.show', $sous_categorie->Id_SC)}}">{{$sous_categorie->NomSC}}</a>
            </div>
    
            @endif
        @endforeach    
    </div>

    <div class="card" >
        <header class="card-header">
            <h5 class="card-header-title">Intérieur</h5>
        </header>
        @foreach($sous_categories as $sous_categorie)
            @if($sous_categorie->Id_C == 2)
            <div class="list-group-item" style="text-align: center;">
                <a href="{{route('sous_categorie.show', $sous_categorie->Id_SC)}}">{{$sous_categorie->NomSC}}</a>
            </div>
            @endif
        @endforeach    
    </div>

@endsection